pg:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: jaffle
      password: jaffle
      dbname: jaffle_shop
      schema: dbt_tuto
      search_path: dbt_tuto,public
      threads: 4
      #sslmode: verify-ca
      #sslrootcert: mkcert/rootCA.pem
    prod:
      type: postgres
      host: postgres
      port: 5432
      user: jaffle
      password: jaffle
      dbname: jaffle_shop
      schema: dbt_prod
      search_path: dbt_prod,public
      threads: 4
      #sslmode: verify-ca
      #sslrootcert: mkcert/rootCA.pem

duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      # You can use a relative path (resolved relative to your profiles.yml file)
      path: '../tuto.duckdb'
      schema: dbt_tuto
      threads: 1
      # threads: 1  (for log_query_path to work)
      #settings:
      #  log_query_path: '../tuto_query.log'
    prod:
      type: duckdb
      # You can use a relative path (resolved relative to your profiles.yml file)
      path: '../tuto.duckdb'
      schema: dbt_prod
      threads: 1
      # threads: 1  (for log_query_path to work)
      #settings:
      #  log_query_path: '../tuto_query.log'